### ISSUE TITLE
Compile Error in Flutter Beta 3.19.0

### ISSUE THREAD

**Issue by jemcmullin** [GIfatahTH/navigation_builder#6]
Using a package which depends on states_rebuilder which depends on this package. Unable to compile while using the Flutter Beta channel at version 3.19.0-0.1.pre . This does not occur on the Stable channel Flutter 3.16.7 .

Error:

> ../../.pub-cache/hosted/pub.dev/navigation_builder-0.0.3/lib/src/rm_scaffold.dart:102:3: Error: Expected 0 type arguments.
  PersistentBottomSheetController<T> showBottomSheet<T>(
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dev/navigation_builder-0.0.3/lib/src/rm_scaffold.dart:124:29: Error: Expected 0 type arguments.
    final r = scaffoldState.showBottomSheet<T>(
                            ^
Unhandled exception:
Unsupported operation: Unsupported invalid type InvalidType(<invalid>) (InvalidType). Encountered while compiling /.pub-cache/hosted/pub.dev/navigation_builder-0.0.3/lib/src/navigation_builder.dart, which contains the type: FunctionType(<invalid>
Function<T>(Widget, {backgroundColor: Color?, clipBehavior: Clip?, constraints: BoxConstraints?, elevation: double?, enableDrag: bool?, shape: ShapeBorder?, transitionAnimationController: AnimationController?})).

**Comment by jgfoster** [comment]
And now that 3.19.0 is released, we are seeing this as well. Perhaps it is related to https://github.com/flutter/flutter/pull/137791/files.

**Comment by karnadii** [comment]
I use @jgfoster patch for now until the PR merged
```yaml
  navigation_builder:
    git: 
      url: https://github.com/jgfoster/navigation_builder.git
      ref: jgfoster-patch-1
```

if you use states_rebuilder too then you have to clone states_rebuilder to your pc, change the pubspec.yml of states rebuilder dependency like above. and reference states_rebuilder locally from your pc to you project.

or use my repo that already use @jgfoster patch
```yaml
  states_rebuilder:
    git:
      url: git@github.com:karnadii/states_rebuilder.git
      ref: 3.19-patch
      path: states_rebuilder_package/
```
